### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by kuragehimekurara1**
Japanese translation is complete. Please confirm it is.

### CODE REVIEW

**Comment by kuragehimekurara1** [comment]
> Hi @kuragehimekurara1 ! Thanks for your contribution. Please put your language file into Japanese.json and restore original English.json so I could merge this.

I created a Japanese.json file and added a Japanese translation to it.  I also restored the translation of the English.json file.  How about this?

**Comment by v-atamanenko** [comment]
Looks good to me, have you tested it in game?

**Comment by kuragehimekurara1** [comment]
> Looks good to me, have you tested it in game?

No, I haven't tested it in the game yet.  How do I test it?

**Comment by v-atamanenko** [comment]
First, make sure that you're on the latest version (1.20). It's easy to know whether you're on 1.20 if your Settings look like this:
image

To install the translation, just drop your `Japanese.json` file to `ux0:/data/osu/languages/`, and select Japanese in settings.

**Comment by kuragehimekurara1** [comment]
> First, make sure that you're on the latest version (1.20). It's easy to know whether you're on 1.20 if your Settings look like this:
> 
> image
> 
> 
> 
> To install the translation, just drop your `Japanese.json` file to `ux0:/data/osu/languages/`, and select Japanese in settings.

I checked (tested) it on a Japanese PS Vita machine, but the characters are garbled where Chinese characters are used.

**Comment by v-atamanenko** [comment]
@kuragehimekurara1 please make sure that you use `primary.ttf` (ux0:/data/osu/skins/default/fonts/primary.ttf) from latest `data-clean.zip`. As I see, it's still the old font for you, it had limited character support.

**Comment by kuragehimekurara1** [comment]
> @kuragehimekurara1 please make sure that you use primary.ttf (ux0:/data/osu/skins/default/fonts/primary.ttf) from latest data-clean.zip. As I see, it's still the old font for you, it had limited character support.

Using the latest data-clean.zip primary.ttf fixed the garbled characters.  As a result of testing, some translations were mistranslated, so I corrected it!

**Comment by kuragehimekurara1** [comment]
I would like to translate osu-octave into Chinese later, so I would appreciate it if you could wait.

**Comment by kuragehimekurara1** [comment]
> I would like to translate osu-octave into Chinese later, so I would appreciate it if you could wait.

Chinese (Simplified) translation completed

**Comment by kuragehimekurara1** [comment]
I tested Chinese (Simplified) translation on the actual machine, but some characters are not displayed even if I use the latest primary.ttf.image

Please forgive it for not being a screenshot.

**Comment by v-atamanenko** [comment]
@kuragehimekurara1 here. Place this `primary_chinese.ttf` in `ux0:data/osu/skins/default/fonts/` (obviously, unpack first from .zip):
[primary_chinese.ttf.zip](https://github.com/v-atamanenko/osu-octave/files/8594498/primary_chinese.ttf.zip)

And then install this vpk.
[osu-octave.vpk.zip](https://github.com/v-atamanenko/osu-octave/files/8594524/osu-octave.vpk.zip)

Chinese should work good in this test build, please check if you can.

On the side note, would be great if you could shorten this line in Japanese:
Screenshot 2022-04-30 at 00 13 08

**Comment by kuragehimekurara1** [comment]
> @kuragehimekurara1 here. Place this `primary_chinese.ttf` in `ux0:data/osu/skins/default/fonts/` (obviously, unpack first from .zip):
> 
> [primary_chinese.ttf.zip](https://github.com/v-atamanenko/osu-octave/files/8594498/primary_chinese.ttf.zip)
> 
> 
> 
> And then install this vpk.
> 
> [osu-octave.vpk.zip](https://github.com/v-atamanenko/osu-octave/files/8594524/osu-octave.vpk.zip)
> 
> 
> 
> Chinese should work good in this test build, please check if you can.
> 
> 
> 
> On the side note, would be great if you could shorten this line in Japanese:
> 
> Screenshot 2022-04-30 at 00 13 08

As a result of the test, I was able to confirm that Chinese works.  Also fixed the translation circled in red

**Comment by kuragehimekurara1** [comment]
> @kuragehimekurara1 here. Place this `primary_chinese.ttf` in `ux0:data/osu/skins/default/fonts/` (obviously, unpack first from .zip):
> 
> [primary_chinese.ttf.zip](https://github.com/v-atamanenko/osu-octave/files/8594498/primary_chinese.ttf.zip)
> 
> 
> 
> And then install this vpk.
> 
> [osu-octave.vpk.zip](https://github.com/v-atamanenko/osu-octave/files/8594524/osu-octave.vpk.zip)
> 
> 
> 
> Chinese should work good in this test build, please check if you can.
> 
> 
> 
> On the side note, would be great if you could shorten this line in Japanese:
> 
> Screenshot 2022-04-30 at 00 13 08

As a result of the test, I was able to confirm that Chinese works. 
image
Also fixed the translation circled in red

**Comment by v-atamanenko** [comment]
Great, thank you.

**Pull request merged**
